### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by 21900279** [2022SCYM/TeamProject2022OSS#1]
주제를 무엇으로 정하는게 좋을까? CRUD 기능이 필요한 주제로 정해야 하는데.

**Comment by daiksoul** [comment]
리뷰 작성 및 조회 프로그램?

**Comment by daiksoul** [comment]
즐겨찾기 목록?
To-do List?

**Comment by 21900279** [comment]
리뷰 작성 및 조회 나쁘지 않네. 글 길이만 제한해두면 관리하기도 쉬울 것 같고

**Comment by daiksoul** [comment]
무슨 리뷰로 할까?

**Comment by 21900279** [comment]
OSS 강의에 대한 리뷰 어떰?

**Comment by 21900279** [comment]
~~한 부분이 이해하기 쉬워서 좋았어요 라던가 ~~부분은 이해하기 힘들었어요 라던가

**Comment by 21900279** [comment]
내용은 그런 식으로 나오고 구조체에 작성자 닉네임이랑 리뷰내용, 별점 같은걸 넣으면 될듯

**Comment by daiksoul** [comment]
그럼 structure가 대충
- 작성자
- 내용
- 추천 비추천

또 뭐가 있을까

**Comment by daiksoul** [comment]
별점

**Comment by 21900279** [comment]
오케이 그럼 이걸로 가자

**Comment by daiksoul** [comment]
![image](https://user-images.githubusercontent.com/20792528/166141395-0ee51396-465c-4a03-bcb8-a5914e59087c.png)
이거가 있는디

**Comment by daiksoul** [comment]
주제 정하는건 이렇게 끝내고 다른데서 기능 정하고 할까?
