### ISSUE TITLE
기능 정의

### ISSUE THREAD

**Issue by 21900279** [2022SCYM/TeamProject2022OSS#2]
기능이 CRUD와 데이터 파일 저장/불러오기, 검색 등 포함 10개 이상 인 것 같은데 어떤 기능을 더 추가해야할까?

**Comment by daiksoul** [comment]
일단 CRUD 저장/ 불러오기 로 6개 때울수 있을 거 같고

**Comment by daiksoul** [comment]
검색 항목으로 여러가지 넣으면 될것 같은데

**Comment by 21900279** [comment]
리뷰 추가
리뷰 조회
리뷰 전체조회
리뷰 일부조회(추천만 보기 or 비추천만 보기)
리뷰 조건부 조회(별점 몇점이상)
리뷰 작성자 검색
리뷰 수정
리뷰 삭제
파일 저장
파일 불러오기

**Comment by daiksoul** [comment]
별점이랑, 작성자

**Comment by 21900279** [comment]
근데 기능들이 CRUD포함해서 10개 이상이겠지?

**Comment by daiksoul** [comment]
그렇겠지?

**Comment by daiksoul** [comment]
조회도 목록형으로 간단히 조회해서 일부 정보만 보이게 하고
자세히 보기 기능 넣어서 해도 괜찮을 것 같다

**Comment by 21900279** [comment]
이전까지는 delete 할 때, 삭제하는 번호에서 특정한 값을 바꿔서 삭제 한 것으로 간주 하는 방식으로 했던거 같은데

**Comment by daiksoul** [comment]
나는 포인터 써서 NULL 넣었어

**Comment by 21900279** [comment]
예를 들어, 1번 2번 3번 있을 때 2번을 삭제하고 전체조회하면 1번 3번 이렇게 보여줬잖아

**Comment by daiksoul** [comment]
그렇지

**Comment by daiksoul** [comment]
것도 고칠래?

**Comment by 21900279** [comment]
그냥 중간에 삭제하면 뒤에 있는 목록들 당겨와서 보여주는게 좋을거 같네

**Comment by daiksoul** [comment]
오케이

**Comment by daiksoul** [comment]
typedef struct{  
  char author[10];  
  char content[100];  
  int recommend;  
  int rating;  
}Review

**Comment by 21900279** [comment]
write
read_all
read_recommend
read_conditional
read
search
edit
delete
save
load

**Comment by 21900279** [comment]
이정도인가

**Comment by 21900279** [comment]
여기에 메뉴 보여주는 함수도 있어야겠네
view_menu

**Comment by daiksoul** [comment]
search가 작성자 검색인거지?

**Comment by 21900279** [comment]
ㅇㅇ

**Comment by daiksoul** [comment]
아 그리고 참고로 "`" 이거 쓰면 코드표시 할 수 있음  
`ㅁㄴㅇㄻㄴ`

**Comment by 21900279** [comment]
그거 어케 쓰는거?

**Comment by daiksoul** [comment]
그 1 왼쪽에 있는거

**Comment by daiksoul** [comment]
초 기호인가?

**Comment by 21900279** [comment]
` 이거?

**Comment by daiksoul** [comment]
어 그거

**Comment by 21900279** [comment]
`hello`

**Comment by 21900279** [comment]
오 이거구만

**Comment by daiksoul** [comment]
3개 묶으면 엔터도 받음
```c
printf("hello world");
```
이런식

**Comment by 21900279** [comment]
3개 어케 묶는거?

**Comment by daiksoul** [comment]
연속으로 3개 쳐

**Comment by 21900279** [comment]
`hello`
`world`
`!!!`

**Comment by daiksoul** [comment]
`을 3개 연속

**Comment by 21900279** [comment]
```hello
world
!!!```

**Comment by daiksoul** [comment]
굳  
맨 윗줄은 언어 지정이야

**Comment by 21900279** [comment]
아 그렇구만

**Comment by 21900279** [comment]
```c
printf("hello");
printf(" world");

**Comment by daiksoul** [comment]
```c
printf("여긴 c");
```
```java
System.out.print("여긴 java");
```

**Comment by 21900279** [comment]
이런식이네

**Comment by 21900279** [comment]
그럼 다음으로 넘어가자
